import aqnsim

COMMANDER_NAME = "Alice"
LIEUTENANT_NAMES = ["L1", "L2", "L3", "L4"]
DISTRIBUTOR_NAME = "Distributor"

M = 1

COMMANDER_IS_TRAITOR = True
TRAITOR_INDICES = []
LOYAL_COMMANDER_ORDER = True

SEND_ORDER_ACTION = "SEND_ORDER"
SEND_CV_ACTION = "SEND_CV"
ROUND2_ACTION = "ROUND2_ACTION"
ROUND3_ACTION = "ROUND3_ACTION"

SEC = aqnsim.SECOND
CLASSICAL_CHANNEL_DELAY = 1 * SEC

CHANNEL_LENGTH = 10
ATTENUATION= .00002

N = 1 + len(LIEUTENANT_NAMES)
COMMANDER_QMEMORY_ADDR = N - 1

NUM_PLAYERS = N
NUM_LIEUTENANTS = N - 1
