import aqnsim

COMMANDER_NAME = "Alice"
LIEUTENANT_NAMES = ["L1", "L2", "L3", "L4"]
DISTRIBUTOR_NAME = "Distributor"

M = 1

COMMANDER_IS_TRAITOR = True
TRAITOR_INDICES = []
LOYAL_COMMANDER_ORDER = True

SEND_ORDER_ACTION = "SEND_ORDER"
SEND_CV_ACTION = "SEND_CV"
ROUND2_ACTION = "ROUND2_ACTION"
ROUND3_ACTION = "ROUND3_ACTION"

SEC = aqnsim.SECOND
QSOURCE_NOISE_MODEL = None
QUANTUM_CHANNEL_DELAY = 0 * SEC 
QUANTUM_CHANNEL_NOISE = 0.0
CLASSICAL_CHANNEL_DELAY = 1 * SEC

T1_TIME = 0.00005 * SEC
NOISE_TIME = 0.000001 * T1_TIME

N = 1 + len(LIEUTENANT_NAMES)
COMMANDER_QMEMORY_ADDR = N - 1

NUM_PLAYERS = N
NUM_LIEUTENANTS = N - 1
